name: Build and test solution

on:
  workflow_call:
    inputs:
      createPackage:
        description: Whether or not to create the NuGet package
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      PACKAGE_PATH: artifacts

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Create NuGet package
        #if: ${{ inputs.createPackage }}
        run: >
          dotnet pack
          --configuration Release
          --no-build
          --no-restore
          --output ${{ env.PACKAGE_PATH }}
          -property:RepositoryCommit=${{ env.GITHUB_SHA }}

      - name: Upload NuGet package
        #if: ${{ inputs.createPackage }}
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ env.PACKAGE_PATH }}
          retention-days: 1
